uploads/urls.py
from django.conf.urls import patterns, url

import uploads.views as views

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^view/(?P<uid>\d+)/$', views.DataSetView.as_view(), name='view'),
    url(r'^view/(?P<uid>\d+)/discharge/$', views.DepthDischargeView.as_view(), name='dod'),
    url(r'^view/(?P<uid>\d+)/level/$', views.BatteryLevelFaultView.as_view(), name='levelfault'),
    url(r'^view/(?P<uid>\d+)/powerfault/$', views.PowerFaultView.as_view(), name='powerfault'),
    url(r'^view/(?P<uid>\d+)/energyfault/$', views.EnergyView.as_view(), name='energy'),
    url(r'^view/(?P<uid>\d+)/powerload/$', views.PowerLoadView.as_view(), name='powerload'),
    url(r'^view/(?P<uid>\d+)/energyload/$', views.EnergyLoadView.as_view(), name='energyload'),
    url(r'^view/(?P<uid>\d+)/upload/$', views.FileUploadView.as_view(), name='upload'),
)

vip_gui/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^uploads/', include('uploads.urls', namespace='uploads')),
    url(r'^accounts/', include('registration.backends.simple.urls'))
)

uploads/models.py
from django.db import models


class DataSet(models.Model):
    """This class is the model for each individual dataset."""
    name = models.CharField(max_length=50)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)


class Data(models.Model):
    """This class is the model for each row of data from a given dataset."""
    dataset = models.ForeignKey(DataSet)
    logtime = models.DateTimeField()
    battery_voltage = models.DecimalField(max_digits=4, decimal_places=2)
    gen_current = models.DecimalField(max_digits=4, decimal_places=2)
    gen_voltage = models.DecimalField(max_digits=4, decimal_places=2)
    load_current = models.DecimalField(max_digits=4, decimal_places=2)

    class Meta:
        ordering = ['logtime']

    def load_is_above(self, val):
        """This method returns True if the battery is above a certain value."""
        return self.battery_voltage > val

    def load_is_below(self, val):
        """This method returns True if the battery is below a certain value."""
        return self.battery_voltage < val

    def get_gen_power(self):
        return self.gen_voltage * self.gen_current

    def get_load_power(self):
        return self.battery_voltage * self.load_current

    def __str__(self):
        return str(self.logtime)

    class Meta:
        verbose_name_plural = "data"

uploads/forms.py
import csv
from io import StringIO

from django import forms

from uploads.models import Data, DataSet


class UploadForm(forms.Form):
    filename = forms.FileField(max_length=100)
    dsid = forms.IntegerField(widget=forms.HiddenInput())

    def handle_upload(self):
        # Get the dataset data is being appended to
        dataset = DataSet.objects.get(id=self.cleaned_data['dsid'])

        # Get CSV file into string file form
        csvf = StringIO(self.cleaned_data['filename'].read().decode())

        # Put all data into an array
        data = []
        reader = csv.reader(csvf, delimiter=',')
        for row in reader:
            data.append(row)

        # Get rid of first row (headers)
        del data[0]

        # Go through each row in the new dataset and append it
        for row in data:
            self._add_data(dataset, row[0], row[1], row[2], row[3], row[4])

    def _add_data(self, dataset, logtime, b_v, l_i, g_i, g_v):
        Data.objects.get_or_create(
            dataset=dataset,
            logtime=logtime,
            battery_voltage=b_v,
            load_current=l_i,
            gen_current=g_i,
            gen_voltage=g_v)

uploads/views.py
import datetime
import time

from django.db.models import Max, Min, Q
from django.shortcuts import get_object_or_404
from django.views.generic import FormView, ListView

from nvd3 import lineWithFocusChart

from uploads.forms import UploadForm
from uploads.models import Data, DataSet

# Battery level constants
BATTERY_MIN_THRESHOLD = 12 * 0.3
BATTERY_MAX_THRESHOLD = 12 * 1.3


class IndexView(ListView):
    """View for the main screen, which shows a list of uploaded files."""
    model = DataSet
    context_object_name = 'datasets'


class DataSetView(ListView):
    """Shows a list of individual data points from a file."""
    template_name = 'uploads/dataset_view.html'
    paginate_by = 50
    context_object_name = 'data'

    def get_queryset(self):
        """Returns a list of data for a given upload."""
        self.dataset = get_object_or_404(DataSet, id=self.kwargs['uid'])
        return Data.objects.filter(dataset=self.dataset)

    def get_context_data(self, **kwargs):
        """
        Adds a reference to the upload to the context passed to
        the template.
        """
        context = super(DataSetView, self).get_context_data(**kwargs)
        context['dataset'] = self.dataset
        return context


class FileUploadView(FormView):
    form_class = UploadForm
    template_name = 'uploads/upload_form.html'
    success_url = '../'

    def get_initial(self):
        initial = super(FileUploadView, self).get_initial()
        initial['dsid'] = self.kwargs['uid']
        return initial

    def form_valid(self, form):
        form.handle_upload()
        return super(FileUploadView, self).form_valid(form)


class BatteryLevelFaultView(DataSetView):
    """
    Displays a list of faults, currently any time the value is outside a specific
    range.
    """
    template_name = 'uploads/batterylevelfault_view.html'


    # Get data from database, but only the points where the battery voltage is outwith the desired range
    def get_queryset(self):
        """Returns a list of 'faulty' data points"""
        data = super(BatteryLevelFaultView, self).get_queryset()
        return data.filter(
            Q(battery_voltage__gt=BATTERY_MAX_THRESHOLD) |
            Q(battery_voltage__lt=BATTERY_MIN_THRESHOLD))


    # Main code function
    def get_context_data(self, **kwargs):
        """
        Gets the number of lower and upper bound faults, and adds these to the
        context passed to the template.
        """
        context = super(BatteryLevelFaultView, self).get_context_data(**kwargs)

        lwarn = 0               # No. of Lower warnings
        uwarn = 0               # No. of Upper warnings
        faults = 0              # No. of Faults
        last_logtime = None     # Define this variable. This will store the current date for specific data point

        # Get faulty data points
        warnings = self.get_queryset()
        for warning in warnings:
            # This checks if two warnings have occurred within an hour, If so it increments faults
            if last_logtime:
                delta = warning.logtime - last_logtime
                if delta < datetime.timedelta(hours=1):
                    faults += 1
            last_logtime = warning.logtime      # Redefine the last_logtim with the date of the current datapoint

            # Calculate Number of lower and upper warnings. Function "load_is_below" is defined in models.py
            if warning.load_is_below(BATTERY_MIN_THRESHOLD):
                 lwarn += 1
            else:
                 uwarn += 1

        # Put these in the context passed to html template
        context['lwarn'] = lwarn
        context['uwarn'] = uwarn
        context['faults'] = faults
        return context


class DepthDischargeView(DataSetView):
    template_name = 'uploads/depthdischarge_view.html'

    # Return Max voltage value
    def get_queryset_max(self):
        data = super(DepthDischargeView, self).get_queryset()
        return data.aggregate(Max('battery_voltage'))['battery_voltage__max']

    # Return Min voltage value
    def get_queryset_min(self):
        data = super(DepthDischargeView, self).get_queryset()
        return data.aggregate(Min('battery_voltage'))['battery_voltage__min']

    ####################################################################################

    ## Ideally the following process will pull in previous Average DOD.
    ## At the moment it is taking the previous average DOD to be 0.

    ## This may not be needed however. The upload process now appends data into a single database.
    ## So each time this code runs it will import the entire data.
    ## When this process was originally created it was envisioned to upload new data to a different file.

    ####################################################################################


    def get_context_data(self, **kwargs):
        context = super(DepthDischargeView, self).get_context_data(**kwargs)

        ##### Data Imported from previous uploads
        AvDOD = 0
        totaluploads = 0
        total = (AvDOD/100)*12 * totaluploads   # = zero for now.
        ####

        ####################################################

        ## Make prediction of lifetime based on DOD

        ####################################################

        preditcion = 0
        fault = 0
        totaluploads = totaluploads + 1


        min = self.get_queryset_min()       # Get min
        max = self.get_queryset_max()       # Get max
        total = total + float(min)

        AvDOD = 100 - ((total/totaluploads)/12 * 100)

        if AvDOD >= 80:
            prediction = 0
            fault = 1;
        if AvDOD >= 60 and AvDOD < 80:
            prediction = 400            ## Cycles required to reduce batter to under 50% capacity
        if AvDOD >= 40 and AvDOD < 60:
            prediction = 600
        if AvDOD > 30 and AvDOD < 40:
            prediction = 1200
        if AvDOD >= 0 and AvDOD <= 30:
            prediction = 1500

        # Pass Data to html file through context
        context['min'] = min
        context['max'] = max
        context['AvDOD'] = AvDOD

        context['prediction']=prediction
        if fault == 1:
            context['diagnosis'] = 'Battery is being discharged too much!!!'
        if fault == 0:
            context['diagnosis'] = 'Battery is Being Discharged to a safe level'




        ####################################################

        ## Categorise Charge/Discharge Cycel

        ####################################################

        Date = 0    ## This is te date of the last good charge discharge cycle. This will also be imported from the last upload

        ####

        new = 0
        Report = ''

        if max < 11:
            Report = Report + 'Battery was not charged fully.'

        if max > 11:
            if AvDOD >= 50:
                Date = now.logtime
                new = 1
                Report = Report + 'Depth of discharge exceeded 50%.'
            if AvDOD < 50:
                Report = Report + 'Battery was not discharged enough.'


        if new == 1:
            Report = 'Battery went throuhg a proper cycle today. '+Report
        if new == 0:
            Report = 'Battery did not go though a proper cycle today. '+Report

        context['date'] = Date
        context['report'] =Report



        ####################################################

        ## Current battery voltage capacity as a percentage of initial battery capacity(12 V)

        ####################################################
        totalcapacity = 0    ## Data saved from last upload

        ####

        capacity = ((totalcapacity*totaluploads)*12)/100

        capacity = capacity + float(max)

        totalcapacity = ((capacity/totaluploads)/12)*100

        context['capacity']= totalcapacity

        return context


class PowerFaultView(DataSetView):
    template_name = 'uploads/powerfault_view.html'

    def get_queryset(self):
        data = super(PowerFaultView, self).get_queryset()
        return data


    def get_context_data(self, **kwargs):
        context = super(PowerFaultView, self).get_context_data(**kwargs)


        D = self.get_queryset()     # Get data set. Unfortunately this imports all data fields so is not very efficient

        # Initialise "a few" variables

        D_total_power = 0

        M_total_power = 0
        Daily_Power = []
        D_dates = []
        Monthly_Power = []
        W_dates = []
        M_dates = []
        Y_dates = []

        Weekly_Power = []
        W_Total_Power = 0


        days = 0
        weeks = 0
        months = 0

        d_count = 0
        w_count = 0
        m_count = 0

        m_d = []


        # Define the last logtime as the logtime of the first element.
        last_logtime = D[0].logtime


        for i in D:
            if last_logtime:
                ## Get Average Daily Power
                if (i.logtime.date() == last_logtime.date()):       ## If the data point has the same day as the previous

                    # "get_gen_power" function is defined in "models.py"
                    D_total_power = D_total_power + i.get_gen_power()   ## Sum power to get the total in a day
                    d_count = d_count + 1                               ## Get number of data points

                else:
                    Daily_Power.append(D_total_power/d_count)                           # Divide by the number of data points to get the average instantanious power
                    D_dates.append(int(time.mktime(last_logtime.timetuple())) * 1000)   # Required Date format for graphs


                    # Same for weeks
                    if days % 7 != 0 or days ==0:
                        W_Total_Power = W_Total_Power + D_total_power
                        w_count = w_count + d_count

                    if days % 7 == 0 and days != 0:

uploads/templates/uploads/Energy_view.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Energy for {{ dataset.name }}{% endblock %}


{% block extrahead %}
        <link href="{% static 'uploads/css/nv.d3.css' %}" rel="stylesheet" type="text/css">
        <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
        <script src="{% static 'uploads/js/nv.d3.min.js' %}" charset="utf-8" /></script>
{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>Energy For {{ dataset.name }}</h1>
    </div>

    <div>
        <a class="btn btn-primary" href="{% url 'uploads:view' dataset.id %}">Back to view</a>
    </div>
    <br />


    {{ chart1|safe }}

    <!--. Commented because the charts are interfering with each other for some reason. One chart is good enough....

     <div>
     {{ chart2|safe }}
     </div>

     <div>
     {{ chart3|safe }}
     </div>

     ..-->


    <div>
        <p>The Average Energy Per Day: {{ D_av_energy }}</p>
        <p>The Average Energy Per Week: {{ W_av_energy }}</p>
        <p>The Average Energy Per Month: {{ M_av_energy }}</p>
        <p>The number of Days below 85 % of the Average: {{ dbelow }}</p>
        <p>The number of Days above 115 % of the Average: {{ dabove }}</p>
        <p>The number of Weekss below 85 % of the Average: {{ wbelow }}</p>
        <p>The number of Weekss above 115 % of the Average: {{ wabove }}</p>
        <p>The number of Months below 85 % of the Average: {{ mbelow }}</p>
        <p>The number of Months above 115 % of the Average: {{ mabove }}</p>
    </div>

    <table class="table">
        <tr>
            <th>Date</th>
            <th>Daily Energy (Kilo-Watt-Hour)</th>
        </tr>
        {% for row in table1 %}
        <tr>
            <td>{{ row.date }}</a></td>
            <td>{{ row.Daily_Energy }}</td>
        </tr>
        {% endfor %}
    </table>

    <table class="table">
        <tr>
            <th>Date</th>
            <th>Weekly Energy (Kilo-Watt-Hour)</th>
        </tr>
        {% for row in table2 %}
        <tr>
            <td>{{ row.date }}</a></td>
            <td>{{ row.Weekly_Energy }}</td>
        </tr>
        {% endfor %}
    </table>


    <table class="table">
        <tr>
            <th>Month</th>
            <th>Year</th>
            <th>Monthly Energy (Kilo-Watt-Hour)</th>
        </tr>
        {% for row in table3 %}
        <tr>
            <td>{{ row.date }}</a></td>
            <td>{{ row.Year }}</a></td>
            <td>{{ row.Monthly_Energy }}</td>
        </tr>
        {% endfor %}
    </table>




{% endblock %}

uploads/templates/uploads/Energyload_view.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Energy for {{ dataset.name }}{% endblock %}


{% block extrahead %}
        <link href="{% static 'uploads/css/nv.d3.css' %}" rel="stylesheet" type="text/css">
        <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
        <script src="{% static 'uploads/js/nv.d3.min.js' %}" charset="utf-8" /></script>
{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>Energy For {{ dataset.name }}</h1>
    </div>

    <div>
        <a class="btn btn-primary" href="{% url 'uploads:view' dataset.id %}">Back to view</a>
    </div>
    <br />

    {{ chart1|safe }}


    <!--. Commented because the charts are interfering with each other for some reason. One chart is good enough....

     <div>
     {{ chart2|safe }}
     </div>

     <div>
     {{ chart3|safe }}
     </div>

     ..-->

    <div>
        <p>The Average Energy Per Day: {{ D_av_energy }}</p>
        <p>The Average Energy Per Week: {{ W_av_energy }}</p>
        <p>The Average Energy Per Month: {{ M_av_energy }}</p>
        <p>The number of Days below 85 % of the Average: {{ dbelow }}</p>
        <p>The number of Days above 115 % of the Average: {{ dabove }}</p>
        <p>The number of Weekss below 85 % of the Average: {{ wbelow }}</p>
        <p>The number of Weekss above 115 % of the Average: {{ wabove }}</p>
        <p>The number of Months below 85 % of the Average: {{ mbelow }}</p>
        <p>The number of Months above 115 % of the Average: {{ mabove }}</p>
    </div>

    <table class="table">
        <tr>
            <th>Date</th>
            <th>Daily Energy (Watt-Hour)</th>
        </tr>
        {% for row in table1 %}
        <tr>
            <td>{{ row.date }}</a></td>
            <td>{{ row.Daily_Energy }}</td>
        </tr>
        {% endfor %}
    </table>

    <table class="table">
        <tr>
            <th>Date</th>
            <th>Weekly Energy (Watt-Hour)</th>
        </tr>
        {% for row in table2 %}
        <tr>
            <td>{{ row.date }}</a></td>
            <td>{{ row.Weekly_Energy }}</td>
        </tr>
        {% endfor %}
    </table>


    <table class="table">
        <tr>
            <th>Month</th>
            <th>Year</th>
            <th>Monthly Energy (Watt-Hour)</th>
        </tr>
        {% for row in table3 %}
        <tr>
            <td>{{ row.date }}</a></td>
            <td>{{ row.Year }}</a></td>
            <td>{{ row.Monthly_Energy }}</td>
        </tr>
        {% endfor %}
    </table>




{% endblock %}

uploads/templates/uploads/batterylevelfault_view.html
{% extends 'base.html' %}

{% block title %}Battery level faults for {{ dataset.name }}{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>Battery level faults for {{ dataset.name }}</h1>
    </div>

    <div>
        <a class="btn btn-primary" href="{% url 'uploads:view' dataset.id %}">Back to view</a>
    </div>
    <br />

    <!-- Pagination -->
    {% if data %}
    <div class="pagination">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
        </span>
    </div>
    {% endif %}

    <!-- Faults -->
    <div class="row large-text">
        <div class="col-xs-4">
        {% if lwarn > 0 %}
            <p class="bg-warning">Number of lower bound warnings: {{ lwarn }}</p>
        {% else %}
            <p class="bg-success">No lower bound warnings</p>
        {% endif %}
        </div>
        <div class="col-xs-4">
        {% if uwarn > 0 %}
            <p class="bg-warning">Number of upper bound warnings: {{ uwarn }}</p>
        {% else %}
            <p class="bg-success">No upper bound warnings</p>
        {% endif %}
        </div>
        <div class="col-xs-4">
        {% if faults > 0 %}
            <p class="bg-danger">Number of faults: {{ faults }}</p>
        {% else %}
            <p class="bg-success">No faults</p>
        {% endif %}
        </div>
    </div>

    <!-- Fault table -->
    {% if data %}
    <table class="table">
        <tr>
            <th>Log Time</th>
            <th>Generator Voltage</th>
            <th>Generator Current</th>
            <th>Load Voltage</th>
            <th>Load Current</th>
        </tr>
    {% for row in data %}
        <tr>
            <td>{{ row.logtime }}</td>
            <td>{{ row.gen_voltage }}</td>
            <td>{{ row.gen_current }}</td>
            <td>{{ row.load_voltage }}</td>
            <td>{{ row.load_current }}</td>
        </tr>
    {% endfor %}
    </table>
    {% endif %}
{% endblock %}

uploads/templates/uploads/dataset_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Locations{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>Choose a Location</h1>
    </div>
    <div class="row">
    {% for dataset in datasets %}
        <div class="col-md-6">
            <a href="{% url 'uploads:view' dataset.id %}">
                <img src="{% get_static_prefix %}uploads/images/{{ dataset.name }}.png" alt="Flag of {{ dataset.name }}" />
            </a>
        </div>
    {% endfor %}
{% endblock %}

uploads/templates/uploads/dataset_view.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ dataset.name }}{% endblock %}


{% block extrahead %}
<link href="{% static 'uploads/css/nv.d3.css' %}" rel="stylesheet" type="text/css">
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="{% static 'uploads/js/nv.d3.min.js' %}" charset="utf-8" /></script>
{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>{{ dataset.name }}</h1>
    </div>
    <div>
        <a class="btn btn-default" href="{% url 'uploads:levelfault' dataset.id %}">Battery Level Faults</a>
        <a class="btn btn-default" href="{% url 'uploads:dod' dataset.id %}">Depth of Discharge</a>
        <a class="btn btn-default" href="{% url 'uploads:powerfault' dataset.id %}">Generated Power</a>
        <a class="btn btn-default" href="{% url 'uploads:energy' dataset.id %}">Generated Energy</a>
        <a class="btn btn-default" href="{% url 'uploads:powerload' dataset.id %}">Dissipated Power</a>
        <a class="btn btn-default" href="{% url 'uploads:energyload' dataset.id %}">Dissipated Energy</a>
        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'uploads:upload' dataset.id %}">Upload New Data</a>
        {% endif %}
    </div>

    <div>
        <p> {{ chart2| safe }} </p>
    </div>

    <!-- Commented because the charts are interfering with each other for some reason. One chart is good enough....

     <div>
        <p> {{ chart1| safe }} </p>
    </div>

     -->

    <div class="pagination">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
        </span>
    </div>
    <table class="table">
        <tr>
            <th>Log time</th>
            <th>Battery Voltage</th>
            <th>Load Current</th>
            <th>Generator Current</th>
            <th>Generator Voltage</th>
        </tr>
    {% for row in data %}
        <tr>
            <td>{{ row.logtime }}</td>
            <td>{{ row.battery_voltage }}</td>
            <td>{{ row.load_current }}</td>
            <td>{{ row.gen_current }}</td>
            <td>{{ row.gen_voltage }}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

uploads/templates/uploads/depthdischarge_view.html
{% extends 'base.html' %}

{% block title %}Depth of discharge for {{ dataset.name }}{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>Depth of discharge for {{ dataset.name }}</h1>
    </div>

    <div>
        <a class="btn btn-primary" href="{% url 'uploads:view' dataset.id %}">Back to view</a>
    </div>
    <br />

    <div>
        <p>The minimum voltage value is: {{ min }}</p>
        <p>The maximum voltage value is: {{ max }}</p>
        <p>The maximum voltage as a percentage of total capacity (12 V) is: {{capacity}}</p>
        <p>The average depth of discharge as a percentage of total capacity (12 V) is: {{ AvDOD }}</p>
        <p>The predicted total number of cycles is: {{prediction}}</p>
        <p>{{diagnosis}}</p>
        <br />
        <p>{{report}}</p>
        {% if date == 0 %}
        <p>This has never been discharged properly</p>
        {% else %}
        <p>The date of the last proper discharge cycle was: {{date}}</p>
        {% endif %}
    </div>


{% endblock %}

uploads/templates/uploads/powerfault_view.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Power faults for {{ dataset.name }}{% endblock %}

{% block extrahead %}
        <link href="{% static 'uploads/css/nv.d3.css' %}" rel="stylesheet" type="text/css">
        <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
        <script src="{% static 'uploads/js/nv.d3.min.js' %}" charset="utf-8" /></script>
{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>Power For {{ dataset.name }}</h1>
    </div>

    <div>
        <a class="btn btn-primary" href="{% url 'uploads:view' dataset.id %}">Back to view</a>
    </div>
    <br />

    <div>
        {{ chart1|safe }}
    </div>

    <!--. Commented because the charts are interfering with each other for some reason. One chart is good enough....

     <div>
        {{ chart2|safe }}
    </div>

    <div>
        {{ chart3|safe }}
    </div>

     ..-->


    <div>
        <p>The Average Power Per Day: {{ D_av_power }}</p>
        <p>The Average Power Per Week: {{ W_av_power }}</p>
        <p>The Average Power Per Month: {{ M_av_power }}</p>
        <p>The number of Days below 85 % of the Average: {{ dbelow }}</p>
        <p>The number of Days above 115 % of the Average: {{ dabove }}</p>
        <p>The number of Weekss below 85 % of the Average: {{ wbelow }}</p>
        <p>The number of Weekss above 115 % of the Average: {{ wabove }}</p>
        <p>The number of Months below 85 % of the Average: {{ mbelow }}</p>
        <p>The number of Months above 115 % of the Average: {{ mabove }}</p>
    </div>

    <table class="table">
        <tr>
            <th>Date</th>
            <th>Daily Power</th>
        </tr>
        {% for row in table1 %}
        <tr>
            <td>{{ row.date }}</a></td>
            <td>{{ row.Daily_Power }}</td>
        </tr>
        {% endfor %}
    </table>

    <table class="table">
        <tr>
            <th>Date</th>
            <th>Weekly Power</th>
        </tr>
        {% for row in table2 %}
        <tr>
            <td>{{ row.date }}</a></td>
            <td>{{ row.Weekly_Power }}</td>
        </tr>
        {% endfor %}
    </table>


    <table class="table">
        <tr>
            <th>Month</th>
            <th>Year</th>
            <th>Monthly Power</th>
        </tr>
        {% for row in table3 %}
        <tr>
            <td>{{ row.date }}</a></td>
            <td>{{ row.Year }}</a></td>
            <td>{{ row.Monthly_Power }}</td>
        </tr>
        {% endfor %}
    </table>

{% endblock %}

uploads/templates/uploads/upload_form.html
{% extends 'base.html' %}

{% block title %}Upload file{% endblock %}

{% block body_block %}
<form role="form" id="page_form" method="post" action="." enctype="multipart/form-data">
    <h2 class="form-heading">Upload a CSV file</h2>
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    <div class="form-group">
        <label for="id_filename">File</label>
        <input type="file" id="id_filename" name="filename">
    </div>

    <button class="btn btn-primary" type="submit" name="submit">Upload</button>
</form>
{% endblock %}